# map paths
map_path: './Spielberg_map'
map_ext: '.png'

# starting pose for map
sx: -0.044081
sy: -0.849163
stheta: 3.4034118

sx2: -3.044081
sy2: -1.349163
stheta2: 3.3949863

# raceline path and indices
wpt_path: './spielberg_lanes.csv'
wpt_delim: ','
wpt_rowskip: 1
# default is (x, y, vel) for each lane/raceline
wpt_xind: 0
wpt_yind: 1
wpt_vind: 2

# seed
seed: 12345

lookahead_distance: 1.3
vgain: 0.75
wheelbase: 0.3302